# Generated by Django 5.1.4 on 2024-12-13 01:13

import blog.utils.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.utils.image_utils.image_upload_path, verbose_name='Featured Image'),
        ),
    ]
